version: "3.7"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    command: --storageEngine wiredTiger
    networks:
      - local-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Mongo2020!

networks:
  local-mongodb:
    driver: bridge
